apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-enable-helm
  namespace: argocd
data:
  kustomized-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-enable-helm
    spec:
      init:
        command: ["/bin/sh", "-c"]
        args: [-c, 'echo "Initializing..."']
      generate:
        command: ["/bin/sh", "-c"]
        args: ["kustomize build --enable-helm"]