apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd

spec:
  source:
    path: app-of-apps/overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true