---
apiVersion: v1
kind: Service
metadata:
  name: internal-2048-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: 2048-app
